// Central configuration for all conversion tools
export const CONVERTERS = [
  {
    slug: "word-to-pdf",
    type: "word",
    icon: "📄",
    title: "Word to PDF",
    description: "Convert Word documents (.docx) to PDF format instantly",
    accept: ".docx",
    endpoint: "/convert/word-to-pdf",
  },
  {
    slug: "html-to-pdf",
    type: "html",
    icon: "🌐",
    title: "HTML to PDF",
    description: "Transform HTML files into professional PDF documents",
    accept: ".html",
    endpoint: "/convert/html-to-pdf",
  },
  {
    slug: "excel-to-pdf",
    type: "excel",
    icon: "📊",
    title: "Excel to PDF",
    description: "Convert Excel spreadsheets to PDF with perfect formatting",
    accept: ".xlsx,.xls",
    endpoint: "/convert/excel-to-pdf",
  },
  {
    slug: "pdf-to-image-pdf",
    type: "pdf-image",
    icon: "🖼️",
    title: "PDF to Image PDF",
    description: "Convert PDF files to image-based PDF format",
    accept: ".pdf",
    endpoint: "/convert/pdf-to-image-pdf",
  },
  {
    slug: "pdf-to-image",
    type: "pdf-to-image",
    icon: "📷",
    title: "PDF to Image",
    description: "Extract PDF pages as image files (PNG, JPG)",
    accept: ".pdf",
    endpoint: "/convert/pdf-to-image",
    isPdfToImage: true,
  },
  {
    slug: "merge-pdf",
    type: "merge",
    icon: "🔗",
    title: "Merge PDF",
    description: "Combine multiple PDF files into a single document",
    accept: ".pdf",
    endpoint: "/merge-pdf",
    isMerge: true,
  },
  {
    slug: "compress-pdf",
    type: "compress",
    icon: "🗜️",
    title: "Compress PDF",
    description: "Reduce PDF file size with different compression levels",
    accept: ".pdf",
    endpoint: "/compress-pdf",
    isCompress: true,
  },
  {
    slug: "pdf-to-word",
    type: "pdf-to-word",
    icon: "📝",
    title: "PDF to Word",
    description: "Convert PDF documents to editable Word format",
    accept: ".pdf",
    endpoint: "/convert/pdf-to-word",
  },
  {
    slug: "image-to-pdf",
    type: "image-to-pdf",
    icon: "🖼️",
    title: "Image to PDF",
    description: "Convert images (JPG, PNG, etc.) to PDF format",
    accept: ".jpg,.jpeg,.png,.gif,.bmp",
    endpoint: "/convert/image-to-pdf",
  },
  {
    slug: "split-pdf",
    type: "split",
    icon: "✂️",
    title: "Split PDF",
    description: "Extract specific pages from a PDF document",
    accept: ".pdf",
    endpoint: "/split-pdf",
    isSplit: true,
  },
  {
    slug: "rotate-pdf",
    type: "rotate",
    icon: "🔄",
    title: "Rotate PDF",
    description: "Rotate PDF pages by 90, 180, or 270 degrees",
    accept: ".pdf",
    endpoint: "/rotate-pdf",
    isRotate: true,
  },
  {
    slug: "protect-pdf",
    type: "protect",
    icon: "🔐",
    title: "Protect PDF",
    description: "Add password protection to your PDF files",
    accept: ".pdf",
    endpoint: "/protect-pdf",
    isProtect: true,
  },
  {
    slug: "pdf-to-text",
    type: "pdf-to-text",
    icon: "📄",
    title: "PDF to Text",
    description: "Extract text content from PDF documents",
    accept: ".pdf",
    endpoint: "/convert/pdf-to-text",
  },
  {
    slug: "watermark-pdf",
    type: "watermark",
    icon: "💧",
    title: "Watermark PDF",
    description: "Add text watermark to your PDF documents",
    accept: ".pdf",
    endpoint: "/watermark-pdf",
    isWatermark: true,
  },
];

export const findConverterBySlug = (slug) =>
  CONVERTERS.find((c) => c.slug === slug);

